function escapeJsonForScript(value: string): string {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}

export function localBridgeDashboardHtml(token: string): string {
  const encodedToken = escapeJsonForScript(token);
  const html = String.raw`<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>repo-harness V6 直接变更控制台</title>
<style>
:root{color-scheme:light;--bg:#f4f6fa;--surface:#fff;--surface2:#f8fafc;--text:#182033;--muted:#69758a;--line:#e2e7ef;--brand:#5147e5;--green:#07875f;--amber:#b86508;--red:#ce3045;--blue:#2465d8;--side:#101725;--shadow:0 14px 38px rgba(31,42,68,.09)}
[data-theme=dark]{color-scheme:dark;--bg:#090e16;--surface:#141b26;--surface2:#0f1621;--text:#eef3f8;--muted:#9aa6b9;--line:#293447;--brand:#818cf8;--green:#34d399;--amber:#fbbf24;--red:#fb7185;--blue:#60a5fa;--side:#070b12;--shadow:0 18px 48px rgba(0,0,0,.3)}
*{box-sizing:border-box}html,body{height:100%}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.app{min-height:100%;display:grid;grid-template-columns:250px minmax(0,1fr)}
.sidebar{position:sticky;top:0;height:100vh;background:var(--side);padding:20px 14px;color:#dce5f5;display:flex;flex-direction:column;gap:18px}.brand{display:flex;gap:11px;align-items:center;padding:2px 8px}.mark{width:42px;height:42px;border-radius:13px;background:linear-gradient(135deg,#6366f1,#9333ea);display:grid;place-items:center;font-weight:900;color:white}.brand strong{display:block}.brand small{color:#8d9bb0}.nav{display:grid;gap:4px}.nav button{border:0;background:transparent;color:#9eabc0;padding:10px 12px;border-radius:10px;text-align:left;cursor:pointer;display:flex;gap:9px;align-items:center}.nav button:hover,.nav button.active{background:rgba(255,255,255,.09);color:white}.nav .count{margin-left:auto;background:rgba(255,255,255,.12);border-radius:999px;padding:1px 7px;font-size:11px}.sideFoot{margin-top:auto;padding:13px;border:1px solid rgba(255,255,255,.1);border-radius:12px;background:rgba(255,255,255,.04);font-size:12px}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#34d399;margin-right:7px;box-shadow:0 0 0 5px rgba(52,211,153,.12)}.repo{margin-top:8px;color:#8996aa;word-break:break-all}
.main{min-width:0}.top{height:72px;position:sticky;top:0;z-index:20;display:flex;align-items:center;justify-content:space-between;padding:0 26px;background:color-mix(in srgb,var(--surface) 92%,transparent);backdrop-filter:blur(16px);border-bottom:1px solid var(--line)}.top h1{margin:0;font-size:20px}.top p{margin:1px 0 0;color:var(--muted);font-size:12px}.toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.content{padding:22px 26px 42px;max-width:1720px;margin:auto}.view{display:none}.view.active{display:block}
button,input,select,textarea{font:inherit}button{border:1px solid var(--line);background:var(--surface);color:var(--text);border-radius:9px;padding:8px 11px;cursor:pointer}button:hover{border-color:color-mix(in srgb,var(--brand) 45%,var(--line))}button.primary{background:var(--brand);border-color:var(--brand);color:white}button.success{background:var(--green);border-color:var(--green);color:white}button.danger{color:var(--red)}button:disabled{opacity:.5;cursor:not-allowed}.icon{width:38px;height:38px;padding:0;display:grid;place-items:center}input,select,textarea{border:1px solid var(--line);background:var(--surface);color:var(--text);border-radius:9px;padding:9px 10px}
.grid{display:grid;gap:16px}.metrics{grid-template-columns:repeat(6,minmax(130px,1fr));margin-bottom:16px}.metric,.panel,.focusCard{background:var(--surface);border:1px solid var(--line);border-radius:15px}.metric{padding:15px 16px}.metric span{display:block;color:var(--muted);font-size:12px}.metric strong{display:block;font-size:26px;margin-top:4px}.metric small{color:var(--muted)}.layout2{grid-template-columns:minmax(0,1.55fr) minmax(330px,.75fr)}.panel{overflow:hidden}.panelHead{padding:16px 18px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.panelHead h2{margin:0;font-size:15px}.panelHead p{margin:3px 0 0;color:var(--muted);font-size:12px}.panelBody{padding:16px 18px}.focusCard{padding:20px;margin-bottom:16px;border-color:color-mix(in srgb,var(--brand) 42%,var(--line));background:linear-gradient(135deg,color-mix(in srgb,var(--brand) 7%,var(--surface)),var(--surface))}.focusTop{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.focusTitle{font-size:20px;font-weight:800}.focusMeta{color:var(--muted);margin-top:4px}.empty{padding:28px 10px;text-align:center;color:var(--muted)}
.badge{display:inline-flex;align-items:center;border:1px solid var(--line);background:var(--surface2);color:var(--muted);border-radius:999px;padding:3px 8px;font-size:11px;font-weight:700}.badge.green{color:var(--green)}.badge.amber{color:var(--amber)}.badge.red{color:var(--red)}.badge.blue{color:var(--blue)}.badge.brand{color:var(--brand)}.notice{padding:12px 14px;border:1px solid var(--line);border-radius:12px;background:var(--surface2);margin-bottom:10px}.notice.critical{border-color:color-mix(in srgb,var(--red) 40%,var(--line));background:color-mix(in srgb,var(--red) 6%,var(--surface))}.notice.warning{border-color:color-mix(in srgb,var(--amber) 40%,var(--line));background:color-mix(in srgb,var(--amber) 6%,var(--surface))}.notice.info{border-color:color-mix(in srgb,var(--blue) 30%,var(--line))}.notice.success{border-color:color-mix(in srgb,var(--green) 35%,var(--line));background:color-mix(in srgb,var(--green) 6%,var(--surface))}.notice strong{display:block}.notice p{margin:3px 0;color:var(--muted);font-size:12px}
.row{border:1px solid var(--line);border-radius:12px;background:var(--surface);padding:12px 14px;display:grid;gap:12px;align-items:center;margin-bottom:9px}.row:hover{box-shadow:var(--shadow)}.issueRow{grid-template-columns:minmax(280px,1.6fr) 120px 130px auto}.taskRow{grid-template-columns:minmax(250px,1.45fr) minmax(180px,.8fr) 130px 140px auto}.runRow{grid-template-columns:minmax(280px,1.5fr) 130px 150px auto}.editRow{grid-template-columns:minmax(300px,1.5fr) 120px 130px 150px auto}.name{font-weight:750}.sub{font-size:12px;color:var(--muted);margin-top:2px}.searchbar{display:flex;gap:8px}.searchbar input{min-width:220px}.progress{height:7px;border-radius:999px;background:var(--surface2);overflow:hidden;margin-top:8px}.progress i{display:block;height:100%;background:linear-gradient(90deg,var(--brand),#8b5cf6)}
.gates{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr));gap:8px}.gate{border:1px solid var(--line);border-radius:10px;padding:10px;background:var(--surface2)}.gate strong{display:block;font-size:12px}.gate span{color:var(--muted);font-size:11px}.gate.pass{border-color:color-mix(in srgb,var(--green) 35%,var(--line))}.gate.fail{border-color:color-mix(in srgb,var(--red) 35%,var(--line))}.detailRow{display:flex;justify-content:space-between;gap:20px;padding:9px 0;border-bottom:1px solid var(--line)}.detailRow span{color:var(--muted)}.event{padding:10px 0;border-bottom:1px solid var(--line)}.event:last-child{border:0}.eventTop{display:flex;justify-content:space-between;gap:10px}.event p{margin:3px 0 0;color:var(--muted);font-size:12px}.code{white-space:pre-wrap;word-break:break-word;background:#0b1020;color:#dbeafe;padding:14px;border-radius:10px;max-height:58vh;overflow:auto;font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}
dialog{border:1px solid var(--line);border-radius:15px;background:var(--surface);color:var(--text);width:min(980px,92vw);max-height:90vh;padding:0;box-shadow:var(--shadow)}dialog::backdrop{background:rgba(5,10,20,.5)}.dialogHead{padding:16px 18px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between}.dialogBody{padding:18px;overflow:auto;max-height:75vh}.dialogHead h3{margin:0}.dialogHead p{margin:2px 0 0;color:var(--muted);font-size:12px}.close{font-size:18px}.toast{position:fixed;right:22px;bottom:22px;background:#111827;color:white;border-radius:10px;padding:11px 14px;opacity:0;transform:translateY(8px);transition:.2s;pointer-events:none;z-index:100}.toast.show{opacity:1;transform:none}
@media(max-width:1100px){.app{grid-template-columns:80px minmax(0,1fr)}.brand div:last-child,.nav button span:not(.count),.sideFoot{display:none}.metrics{grid-template-columns:repeat(3,1fr)}.layout2{grid-template-columns:1fr}.gates{grid-template-columns:repeat(2,1fr)}}
@media(max-width:760px){.app{display:block}.sidebar{position:static;height:auto}.nav{grid-template-columns:repeat(3,1fr)}.top{position:static;height:auto;padding:14px}.content{padding:14px}.metrics{grid-template-columns:repeat(2,1fr)}.row{grid-template-columns:1fr}.gates{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="app">
<aside class="sidebar">
  <div class="brand"><div class="mark">RH</div><div><strong>repo-harness V6</strong><small>Direct Change & Evidence</small></div></div>
  <nav class="nav">
    <button class="active" data-view="overview">⌂ <span>执行中心</span></button>
    <button data-view="changes">✎ <span>文件变更</span><b class="count" id="editCount">0</b></button>
    <button data-view="focus">◎ <span>当前主线</span></button>
    <button data-view="tasks">✓ <span>任务管理</span><b class="count" id="taskCount">0</b></button>
    <button data-view="runs">▶ <span>执行记录</span><b class="count" id="runCount">0</b></button>
    <button data-view="governance">! <span>治理异常</span><b class="count" id="govCount">0</b></button>
    <button data-view="timeline">≡ <span>工作留痕</span></button>
    <button data-view="archive">◇ <span>历史归档</span></button>
    <button data-view="github">⌁ <span>GitHub 插件</span></button>
  </nav>
  <div class="sideFoot"><div><span class="dot"></span><strong id="streamState">正在连接</strong></div><div class="repo" id="repoPath">—</div></div>
</aside>
<main class="main">
<header class="top"><div><h1 id="pageTitle">执行中心</h1><p id="pageSubtitle">小修改直接落地，复杂工作才创建 Issue</p></div><div class="toolbar"><span class="badge brand">controller-direct-change-v6</span><button class="icon" id="themeBtn">◐</button><button id="refreshBtn">刷新</button><button class="primary" id="reconcileBtn">治理并收敛</button></div></header>
<div class="content">
<section class="view active" id="view-overview">
  <div class="notice info"><strong>V6 工作模式</strong><p>已知文件、文档、配置和小范围代码修改默认走直接编辑：读取 → 原子修改 → 查看 Patch → 运行检查 → 完成。只有根因未知、需要依赖图、并行或长时间执行时才创建 Issue。</p></div>
  <div class="grid metrics" id="metrics"></div>
  <div class="grid layout2"><div class="panel"><div class="panelHead"><div><h2>下一步可执行工作</h2><p>当前主线 Ready Task 与尚未完成的直接编辑</p></div><button class="primary" id="launchAllBtn">执行当前 Ready Tasks</button></div><div class="panelBody" id="nextWork"></div></div><div class="panel"><div class="panelHead"><div><h2>真实结果</h2><p>只统计已落地并有证据的变更</p></div></div><div class="panelBody" id="evidenceSummary"></div></div></div>
</section>
<section class="view" id="view-changes"><div class="panel"><div class="panelHead"><div><h2>文件变更</h2><p>直接编辑会话、实际文件、Patch、检查和完成状态</p></div><div class="searchbar"><select id="editFilter"><option value="all">全部</option><option value="open">待修改</option><option value="applied">待验证</option><option value="verification_failed">验证失败</option><option value="verified">待完成</option><option value="finalized">已完成</option><option value="rolled_back">已回滚</option></select></div></div><div class="panelBody" id="editList"></div></div></section>
<section class="view" id="view-focus"><div id="focusCard"></div><div class="panel"><div class="panelHead"><div><h2>活动 Issue</h2><p>只有一个 Issue 驱动“全部执行”</p></div><select id="creationMode"><option value="focus_only">focus_only</option><option value="open">open</option><option value="paused">paused</option></select></div><div class="panelBody" id="issueList"></div></div></section>
<section class="view" id="view-tasks"><div class="panel"><div class="panelHead"><div><h2>任务管理</h2><p>复杂工作使用 Task；普通文档和小改动不应出现在这里</p></div><div class="searchbar"><input id="taskSearch" placeholder="搜索任务"/><select id="taskFilter"><option value="all">全部状态</option><option value="ready">ready</option><option value="running">running</option><option value="review">review</option><option value="verified">verified</option><option value="blocked">blocked</option></select></div></div><div class="panelBody" id="taskList"></div></div></section>
<section class="view" id="view-runs"><div class="panel"><div class="panelHead"><div><h2>执行记录</h2><p>Agent Run 是一次尝试，不等于 Task 完成</p></div></div><div class="panelBody" id="runList"></div></div></section>
<section class="view" id="view-governance"><div class="panel"><div class="panelHead"><div><h2>治理异常</h2><p>失效依赖、停滞审核、重复 Issue 和无可执行主线</p></div><button class="primary" onclick="reconcile()">治理并收敛</button></div><div class="panelBody" id="governanceList"></div></div></section>
<section class="view" id="view-timeline"><div class="panel"><div class="panelHead"><div><h2>工作留痕</h2><p>Issue、Task、Run、直接编辑、验证和 GitHub 事件</p></div><button id="exportBtn">导出报告</button></div><div class="panelBody" id="timelineList"></div></div></section>
<section class="view" id="view-archive"><div class="panel"><div class="panelHead"><div><h2>历史归档</h2><p>终态工作与当前执行分离</p></div></div><div class="panelBody" id="archiveList"></div></div></section>
<section class="view" id="view-github"><div class="panel"><div class="panelHead"><div><h2>GitHub 插件</h2><p>用于 Issue、Project、PR 和 CI；本地状态仍是事实源</p></div></div><div class="panelBody" id="githubArea"></div></div></section>
</div>
</main>
</div>
<dialog id="editDialog"><div class="dialogHead"><div><h3 id="editDialogTitle">文件变更</h3><p id="editDialogSub"></p></div><button class="close" onclick="editDialog.close()">×</button></div><div class="dialogBody"><div id="editMeta"></div><h4>修改文件</h4><div id="editFiles"></div><h4>检查结果</h4><div id="editChecks"></div><h4>Patch</h4><pre class="code" id="editDiff"></pre><div class="toolbar" id="editActions" style="margin-top:14px"></div></div></dialog>
<dialog id="taskDialog"><div class="dialogHead"><div><h3 id="taskDialogTitle">Task</h3><p id="taskDialogSub"></p></div><button class="close" onclick="taskDialog.close()">×</button></div><div class="dialogBody"><div id="taskOverview"></div><h4>证据门禁</h4><div class="gates" id="taskGates"></div><h4>Run 历史</h4><div id="taskRuns"></div><h4>下一步</h4><div id="taskActions"></div></div></dialog>
<dialog id="runDialog"><div class="dialogHead"><div><h3 id="runDialogTitle">Run</h3><p id="runDialogSub"></p></div><button class="close" onclick="runDialog.close()">×</button></div><div class="dialogBody"><div id="runMeta"></div><h4>日志</h4><pre class="code" id="runLog"></pre></div></dialog>
<div class="toast" id="toast"></div>
<script>
const TOKEN=${encodedToken};let SNAP=null;const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const titles={overview:['执行中心','小修改直接落地，复杂工作才创建 Issue'],changes:['文件变更','查看真正修改了哪些文件、是否验证和完成'],focus:['当前主线','选择唯一的复杂工作执行主线'],tasks:['任务管理','只管理需要持续跟踪的复杂工作'],runs:['执行记录','一次 Run 是尝试，不是完成'],governance:['治理异常','发现并收敛任务状态问题'],timeline:['工作留痕','所有操作和证据的统一时间线'],archive:['历史归档','当前工作与历史记录分离'],github:['GitHub 插件','可选远端协作能力']};
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{'x-repo-harness-local-token':TOKEN,'content-type':'application/json',...(opt.headers||{})}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||('HTTP '+r.status));return body}
function fmt(v){if(!v)return '—';return new Date(v).toLocaleString()}
function cls(s){if(['done','verified','succeeded','finalized'].includes(s))return 'green';if(['failed','blocked','verification_failed'].includes(s))return 'red';if(['running','applied','review','verifying'].includes(s))return 'blue';if(['ready','planned','open'].includes(s))return 'amber';return ''}
function badge(s){return '<span class="badge '+cls(s)+'">'+esc(s||'—')+'</span>'}
function setView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('#view-'+v).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#pageTitle').textContent=titles[v][0];$('#pageSubtitle').textContent=titles[v][1]}
function eventRow(e){return '<div class="event"><div class="eventTop"><strong>'+esc(e.action)+'</strong><span class="sub">'+fmt(e.at)+'</span></div><p>'+esc(e.summary)+' · '+esc(e.editSessionId||e.runId||e.taskId||e.issueId||e.actor)+'</p></div>'}
function gateCard(g){return '<div class="gate '+(g.status==='passed'?'pass':g.status==='failed'?'fail':'')+'"><strong>'+esc(g.label)+'</strong><span>'+esc(g.status)+' · '+esc(g.summary||'')+'</span></div>'}
function allTasks(){return (SNAP.progress.issues||[]).flatMap(i=>(i.tasks||[]).map(t=>({...t,issueId:i.id,issueTitle:i.title})))}
function renderMetrics(){const p=SNAP.progress,g=SNAP.governance,ed=SNAP.editSessions||[];const finalized=ed.filter(x=>x.status==='finalized').length;const pendingEdits=ed.filter(x=>!['finalized','rolled_back'].includes(x.status)).length;const values=[['当前主线',g.currentIssueId?'1':'0',g.currentIssueId||'未选择'],['Ready Tasks',g.executionQueue?.length||0,'可直接启动'],['直接变更待完成',pendingEdits,'无需 Issue'],['已完成直接变更',finalized,'有 Patch 与验证'],['活动 Run',p.activeRunCount||0,'Agent 执行中'],['治理异常',g.findings?.length||0,'需要处理']];$('#metrics').innerHTML=values.map(x=>'<div class="metric"><span>'+x[0]+'</span><strong>'+x[1]+'</strong><small>'+esc(x[2])+'</small></div>').join('')}
function renderOverview(){const queue=SNAP.governance.executionQueue||[];const edits=(SNAP.editSessions||[]).filter(e=>!['finalized','rolled_back'].includes(e.status));let html='';html+=edits.slice(0,5).map(e=>'<div class="notice info"><strong>直接变更 · '+esc(e.purpose)+'</strong><p>'+e.changedFiles+' 个文件 · '+e.changedLines+' 行 · '+esc(e.status)+'</p><button onclick="showEdit(\''+esc(e.sessionId)+'\')">查看并完成</button></div>').join('');html+=queue.slice(0,8).map(q=>'<div class="notice warning"><strong>'+esc(q.title)+'</strong><p>'+esc(q.issueId)+' / '+esc(q.taskId)+' · '+esc(q.effectiveStatus)+'</p><button onclick="launchTask(\''+esc(q.issueId)+'\',\''+esc(q.taskId)+'\')">开始执行</button></div>').join('');$('#nextWork').innerHTML=html||'<div class="empty">当前没有待执行工作</div>';const finalized=(SNAP.editSessions||[]).filter(e=>e.status==='finalized');const doneTasks=allTasks().filter(t=>t.status==='done');$('#evidenceSummary').innerHTML='<div class="detailRow"><span>直接变更已完成</span><strong>'+finalized.length+'</strong></div><div class="detailRow"><span>Task 已接受</span><strong>'+doneTasks.length+'</strong></div><div class="detailRow"><span>最近 7 天吞吐</span><strong>'+esc(SNAP.progress.throughput?.completedLast7Days||0)+'</strong></div><div class="notice success" style="margin-top:12px"><strong>完成定义</strong><p>文件已修改、Patch 已持久化、检查通过并完成确认，才计为真实结果。</p></div>'}
function renderEdits(){const f=$('#editFilter').value;const list=(SNAP.editSessions||[]).filter(e=>f==='all'||e.status===f);$('#editList').innerHTML=list.length?list.map(e=>'<div class="row editRow"><div><div class="name">'+esc(e.purpose)+'</div><div class="sub">'+esc(e.sessionId)+' · '+fmt(e.updatedAt)+'</div><div class="progress"><i style="width:'+(['open'].includes(e.status)?10:['applied','verification_failed'].includes(e.status)?55:e.status==='verified'?80:100)+'%"></i></div></div><div>'+badge(e.status)+'</div><div><strong>'+e.changedFiles+'</strong> 文件<br><span class="sub">'+e.changedLines+' 行</span></div><div>'+e.checksPassed+'/'+e.checksTotal+' 检查</div><div><button onclick="showEdit(\''+esc(e.sessionId)+'\')">查看</button></div></div>').join(''):'<div class="empty">暂无直接编辑记录</div>'}
function renderFocus(){const id=SNAP.governance.currentIssueId;const issue=(SNAP.progress.issues||[]).find(i=>i.id===id);$('#focusCard').innerHTML=issue?'<div class="focusCard"><div class="focusTop"><div><div class="focusTitle">'+esc(issue.title)+'</div><div class="focusMeta">'+esc(issue.id)+' · '+esc(issue.status)+' · '+issue.completedTasks+'/'+issue.totalTasks+' Tasks</div></div><button class="primary" onclick="launchIssue(\''+esc(issue.id)+'\')">执行 Ready Tasks</button></div></div>':'<div class="notice warning"><strong>未选择当前主线</strong><p>只有复杂、需要持续追踪的工作才需要选择 Issue 主线。</p></div>';const issues=(SNAP.progress.issues||[]);$('#issueList').innerHTML=issues.length?issues.map(i=>'<div class="row issueRow"><div><div class="name">'+esc(i.title)+'</div><div class="sub">'+esc(i.id)+'</div></div><div>'+badge(i.status)+'</div><div>'+i.completedTasks+'/'+i.totalTasks+' Tasks</div><div><button onclick="focusIssue(\''+esc(i.id)+'\')">设为主线</button></div></div>').join(''):'<div class="empty">没有活动 Issue</div>';$('#creationMode').value=SNAP.projectState.issueCreationMode||'focus_only'}
function renderTasks(){const q=$('#taskSearch').value.toLowerCase(),f=$('#taskFilter').value;const list=allTasks().filter(t=>(f==='all'||t.effectiveStatus===f||t.status===f)&&(!q||(t.title+' '+t.issueId+' '+t.issueTitle).toLowerCase().includes(q)));$('#taskList').innerHTML=list.length?list.map(t=>'<div class="row taskRow"><div><div class="name">'+esc(t.title)+'</div><div class="sub">'+esc(t.issueId)+' / '+esc(t.taskId)+'</div><div class="progress"><i style="width:'+esc(t.completion?.percent||0)+'%"></i></div></div><div>'+esc(t.currentActivity||'无活动')+'</div><div>'+badge(t.effectiveStatus)+'</div><div>'+esc(t.completion?.summary||'')+'</div><div><button onclick="showTask(\''+esc(t.issueId)+'\',\''+esc(t.taskId)+'\')">详情</button></div></div>').join(''):'<div class="empty">没有匹配任务</div>'}
function renderRuns(){const list=SNAP.runs||[];$('#runList').innerHTML=list.length?list.map(r=>'<div class="row runRow"><div><div class="name">'+esc(r.issueId)+' / '+esc(r.taskId)+'</div><div class="sub">'+esc(r.runId)+' · '+esc(r.agent)+' · '+esc(r.executionMode)+'</div></div><div>'+badge(r.status)+'</div><div>'+fmt(r.progress?.lastActivityAt||r.finishedAt||r.createdAt)+'</div><div><button onclick="showRun(\''+esc(r.runId)+'\')">查看</button>'+(['failed','unknown','cancelled','waiting_for_user'].includes(r.status)?'<button class="primary" onclick="retryLatest(\''+esc(r.runId)+'\')">重试</button>':'')+'</div></div>').join(''):'<div class="empty">暂无 Run</div>'}
function renderGovernance(){const list=SNAP.governance.findings||[];$('#governanceList').innerHTML=list.length?list.map(x=>'<div class="notice '+esc(x.severity)+'"><strong>'+esc(x.code)+' · '+esc(x.recommendedAction)+'</strong><p>'+esc(x.message)+'</p><div class="sub">'+esc([x.issueId,x.taskId,x.runId].filter(Boolean).join(' / '))+(x.autoFixable?' · 可自动修复':' · 需要人工判断')+'</div></div>').join(''):'<div class="empty">治理状态健康</div>'}
function renderTimeline(){const list=SNAP.timeline||[];$('#timelineList').innerHTML=list.length?list.map(eventRow).join(''):'<div class="empty">暂无留痕</div>'}
function renderArchive(){const list=SNAP.progress.archivedIssues||[];$('#archiveList').innerHTML=list.length?list.map(i=>'<div class="row issueRow"><div><div class="name">'+esc(i.title)+'</div><div class="sub">'+esc(i.id)+' · '+fmt(i.archivedAt)+'</div></div><div>'+badge(i.status)+'</div><div>'+i.completedTasks+'/'+i.totalTasks+' Tasks</div><div><button onclick="restoreIssue(\''+esc(i.id)+'\')">恢复</button></div></div>').join(''):'<div class="empty">暂无归档 Issue</div>'}
function renderGithub(){const g=SNAP.githubPlugin;$('#githubArea').innerHTML='<div class="notice '+(g.config?.enabled?'info':'warning')+'"><strong>'+(g.config?.enabled?'插件已启用':'插件未启用')+'</strong><p>'+esc(g.readiness?.message||'GitHub 仅作为可选协作插件。')+'</p></div><div class="detailRow"><span>Repository</span><strong>'+esc(g.config?.repository||'未配置')+'</strong></div><div class="detailRow"><span>同步模式</span><strong>'+esc(g.config?.syncMode||'manual')+'</strong></div><div class="detailRow"><span>Task 子 Issue</span><strong>'+(g.config?.includeTasks?'开启':'关闭')+'</strong></div>'}
function render(){renderMetrics();renderOverview();renderEdits();renderFocus();renderTasks();renderRuns();renderGovernance();renderTimeline();renderArchive();renderGithub();$('#repoPath').textContent=SNAP.repoRoot;$('#editCount').textContent=(SNAP.editSessions||[]).filter(e=>!['finalized','rolled_back'].includes(e.status)).length;$('#taskCount').textContent=allTasks().filter(t=>!['done','cancelled','superseded'].includes(t.status)).length;$('#runCount').textContent=(SNAP.runs||[]).filter(r=>['queued','running','waiting_for_user'].includes(r.status)).length;$('#govCount').textContent=(SNAP.governance.findings||[]).length}
async function refresh(){try{SNAP=await api('/api/snapshot');render()}catch(e){toast(e.message)}}
async function focusIssue(id){try{await api('/api/issues/'+encodeURIComponent(id)+'/focus',{method:'POST'});toast('已设置当前主线');await refresh()}catch(e){toast(e.message)}}
async function launchIssue(id){try{const r=await api('/api/issues/'+encodeURIComponent(id)+'/launch',{method:'POST',body:JSON.stringify({maxParallel:2})});toast('已提交 '+r.jobs.length+' 个任务');await refresh()}catch(e){toast(e.message)}}
async function launchTask(i,t){try{await api('/api/issues/'+encodeURIComponent(i)+'/tasks/'+encodeURIComponent(t)+'/launch',{method:'POST',body:'{}'});toast('已提交执行');await refresh()}catch(e){toast(e.message)}}
async function retryLatest(id){try{await api('/api/runs/'+encodeURIComponent(id)+'/retry',{method:'POST',body:JSON.stringify({timeoutMs:3600000})});toast('已创建重试 Run');await refresh()}catch(e){toast(e.message)}}
async function showEdit(id){try{const [e,d]=await Promise.all([api('/api/edit-sessions/'+encodeURIComponent(id)),api('/api/edit-sessions/'+encodeURIComponent(id)+'/diff')]);$('#editDialogTitle').textContent=e.purpose;$('#editDialogSub').textContent=e.sessionId+' · '+e.status;$('#editMeta').innerHTML=[['状态',e.status],['基线版本',e.baseRevision||'—'],['创建时间',fmt(e.createdAt)],['完成时间',fmt(e.finalizedAt)],['Patch SHA',e.diffSha256||'—']].map(x=>'<div class="detailRow"><span>'+x[0]+'</span><strong>'+esc(x[1])+'</strong></div>').join('');$('#editFiles').innerHTML=e.operations.length?e.operations.map(o=>'<div class="detailRow"><span>'+esc(o.path)+'</span><strong>'+esc(o.type)+' · '+o.changedLines+' 行</strong></div>').join(''):'<div class="empty">尚未应用修改</div>';$('#editChecks').innerHTML=e.checkResults.length?e.checkResults.map(c=>'<div class="notice '+(c.ok?'success':'critical')+'"><strong>'+esc(c.checkId)+' · '+(c.ok?'通过':'失败')+'</strong><p>'+esc(c.summary)+'</p></div>').join(''):'<div class="empty">尚未运行检查</div>';$('#editDiff').textContent=d.patch||'(尚无 Patch)';let a='';if(['applied','verification_failed'].includes(e.status))a+='<button class="primary" onclick="verifyEdit(\''+esc(id)+'\')">运行验证</button>';if(e.status==='verified')a+='<button class="success" onclick="finalizeEdit(\''+esc(id)+'\')">确认完成</button>';if(['applied','verified','verification_failed'].includes(e.status))a+='<button class="danger" onclick="rollbackEdit(\''+esc(id)+'\')">回滚修改</button>';$('#editActions').innerHTML=a;editDialog.showModal()}catch(e){toast(e.message)}}
async function verifyEdit(id){try{await api('/api/edit-sessions/'+encodeURIComponent(id)+'/verify',{method:'POST',body:JSON.stringify({reviewer:'local-controller-human'})});toast('验证已完成');editDialog.close();await refresh();showEdit(id)}catch(e){toast(e.message)}}
async function finalizeEdit(id){if(!confirm('确认 Patch 和检查结果有效，并将此直接变更标记为完成？'))return;try{await api('/api/edit-sessions/'+encodeURIComponent(id)+'/finalize',{method:'POST',body:JSON.stringify({reviewer:'local-controller-human'})});toast('直接变更已完成');editDialog.close();await refresh()}catch(e){toast(e.message)}}
async function rollbackEdit(id){if(!confirm('确认回滚此直接变更？'))return;try{await api('/api/edit-sessions/'+encodeURIComponent(id)+'/rollback',{method:'POST',body:'{}'});toast('修改已回滚');editDialog.close();await refresh()}catch(e){toast(e.message)}}
async function showTask(i,t){try{const d=await api('/api/issues/'+encodeURIComponent(i)+'/tasks/'+encodeURIComponent(t));$('#taskDialogTitle').textContent=d.task.title;$('#taskDialogSub').textContent=i+' / '+t+' · '+d.progress.effectiveStatus;$('#taskOverview').innerHTML='<p>'+esc(d.task.objective)+'</p>'+[['持久状态',d.task.status],['有效状态',d.progress.effectiveStatus],['依赖阻塞',d.progress.blockedBy.join(', ')||'无'],['Run 次数',d.progress.runCount]].map(x=>'<div class="detailRow"><span>'+x[0]+'</span><strong>'+esc(x[1])+'</strong></div>').join('');const c=d.progress.completion;$('#taskGates').innerHTML=[c.execution,c.integration,c.checks,c.acceptance,c.closure].map(gateCard).join('');$('#taskRuns').innerHTML=d.runs.length?d.runs.map(r=>'<button style="display:block;width:100%;margin:5px 0;text-align:left" onclick="taskDialog.close();showRun(\''+esc(r.runId)+'\')">'+esc(r.runId)+' · '+esc(r.status)+'</button>').join(''):'<div class="empty">尚未执行</div>';let a='';if(['ready','changes_requested'].includes(d.task.status))a+='<button class="primary" onclick="launchTask(\''+esc(i)+'\',\''+esc(t)+'\');taskDialog.close()">开始执行</button>';if(['review','integrated','verifying'].includes(d.task.status))a+='<button class="primary" onclick="verifyTask(\''+esc(i)+'\',\''+esc(t)+'\')">运行验证</button>';if(d.task.status==='verified')a+='<button class="success" onclick="acceptTask(\''+esc(i)+'\',\''+esc(t)+'\')">接受并完成</button>';$('#taskActions').innerHTML=a;taskDialog.showModal()}catch(e){toast(e.message)}}
async function verifyTask(i,t){try{await api('/api/issues/'+encodeURIComponent(i)+'/tasks/'+encodeURIComponent(t)+'/verify',{method:'POST',body:JSON.stringify({confirmAcceptance:true,reviewer:'local-controller-human'})});toast('Task 验证完成');taskDialog.close();await refresh()}catch(e){toast(e.message)}}
async function acceptTask(i,t){try{await api('/api/issues/'+encodeURIComponent(i)+'/tasks/'+encodeURIComponent(t)+'/accept',{method:'POST',body:'{}'});toast('Task 已完成');taskDialog.close();await refresh()}catch(e){toast(e.message)}}
async function showRun(id){try{const [r,l]=await Promise.all([api('/api/runs/'+encodeURIComponent(id)),api('/api/runs/'+encodeURIComponent(id)+'/log')]);$('#runDialogTitle').textContent=r.issueId+' / '+r.taskId;$('#runDialogSub').textContent=r.runId+' · '+r.agent;$('#runMeta').innerHTML=[['状态',r.status],['执行模式',r.executionMode],['当前活动',r.progress?.currentActivity||'—'],['开始',fmt(r.startedAt)],['结束',fmt(r.finishedAt)],['错误',r.error||'—']].map(x=>'<div class="detailRow"><span>'+x[0]+'</span><strong>'+esc(x[1])+'</strong></div>').join('');$('#runLog').textContent=l.log||'(暂无输出)';runDialog.showModal()}catch(e){toast(e.message)}}
async function restoreIssue(id){try{await api('/api/issues/'+encodeURIComponent(id)+'/restore',{method:'POST'});toast('已恢复');await refresh()}catch(e){toast(e.message)}}
async function reconcile(){try{const r=await api('/api/governance/reconcile',{method:'POST'});toast(r.changed?'已应用 '+r.changes.length+' 项安全修复':'没有可自动修复项');await refresh()}catch(e){toast(e.message)}}
async function exportWorklog(){try{const r=await api('/api/worklog/export',{method:'POST',body:JSON.stringify({format:'markdown'})});toast('已导出 '+r.path)}catch(e){toast(e.message)}}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#refreshBtn').onclick=refresh;$('#reconcileBtn').onclick=reconcile;$('#launchAllBtn').onclick=()=>SNAP.governance.currentIssueId?launchIssue(SNAP.governance.currentIssueId):toast('当前没有复杂工作主线');$('#exportBtn').onclick=exportWorklog;$('#themeBtn').onclick=()=>{const r=document.documentElement;r.dataset.theme=r.dataset.theme==='dark'?'light':'dark';localStorage.setItem('rh-theme',r.dataset.theme)};$('#creationMode').onchange=async()=>{try{await api('/api/project-state',{method:'PATCH',body:JSON.stringify({issueCreationMode:$('#creationMode').value})});toast('策略已保存');await refresh()}catch(e){toast(e.message)}};$('#taskSearch').oninput=renderTasks;$('#taskFilter').onchange=renderTasks;$('#editFilter').onchange=renderEdits;document.documentElement.dataset.theme=localStorage.getItem('rh-theme')||'light';
const stream=new EventSource('/api/stream?token='+encodeURIComponent(TOKEN));stream.addEventListener('refresh',refresh);stream.onopen=()=>$('#streamState').textContent='实时连接正常';stream.onerror=()=>$('#streamState').textContent='实时连接重试中';refresh();setInterval(refresh,30000);
</script>
</body>
</html>`;
  return html.replace(/\\u([0-9a-fA-F]{4})/g, (match, hex) => {
    const code = Number.parseInt(hex, 16);
    return code >= 0x80 ? String.fromCharCode(code) : match;
  });
}
