import type { RecoveryActionDescriptor } from './types';

export const RECOVERY_ACTIONS = {
  probeAgain: {
    id: 'recovery.probe_again',
    title: 'Run capability probe again',
    description: 'Run the read-only recovery probe again and compare evidence.',
    class: 'unknown',
    risk: 'readonly',
    confirmation: 'none',
    localOnly: true,
    boundedTo: [],
  },
  refreshRepository: {
    id: 'recovery.refresh_repository',
    title: 'Refresh repository metadata',
    description: 'Refresh registered repository and checkout metadata.',
    class: 'local_recoverable',
    risk: 'low',
    confirmation: 'authorization',
    localOnly: true,
    boundedTo: ['registered_repository'],
  },
  rebuildProjection: {
    id: 'recovery.rebuild_projection',
    title: 'Rebuild runtime projection',
    description: 'Rebuild materialized repo-harness runtime projection from durable state.',
    class: 'stale_runtime_state',
    risk: 'low',
    confirmation: 'authorization',
    localOnly: true,
    boundedTo: ['repo_harness_runtime_storage'],
  },
  reconcileJobs: {
    id: 'recovery.reconcile_jobs',
    title: 'Reconcile jobs and leases',
    description: 'Reconcile stale local jobs, terminalize dead work, and refresh runtime state.',
    class: 'stale_runtime_state',
    risk: 'medium',
    confirmation: 'authorization',
    localOnly: true,
    boundedTo: ['repo_harness_runtime_storage'],
  },
  cleanupPreview: {
    id: 'recovery.cleanup_preview',
    title: 'Preview runtime cleanup',
    description: 'Preview stale repo-harness temp dirs, terminal local jobs, and historical attention cleanup candidates.',
    class: 'local_recoverable',
    risk: 'readonly',
    confirmation: 'none',
    localOnly: true,
    boundedTo: ['repo_harness_runtime_storage'],
  },
  restartLocalBridge: {
    id: 'recovery.restart_local_bridge',
    title: 'Restart local bridge',
    description: 'Restart only the repo-harness local bridge process. The current HTTP request may disconnect.',
    class: 'local_recoverable',
    risk: 'medium',
    confirmation: 'authorization',
    localOnly: true,
    boundedTo: ['repo_harness_local_bridge'],
  },
  restartController: {
    id: 'recovery.restart_controller',
    title: 'Restart controller daemon',
    description: 'Restart the repo-harness controller daemon and verify readiness after restart.',
    class: 'local_recoverable',
    risk: 'high',
    confirmation: 'strong_confirmation',
    localOnly: true,
    boundedTo: ['repo_harness_controller_daemon'],
  },
  createSelfFixTask: {
    id: 'recovery.create_self_fix_task',
    title: 'Create self-fix task',
    description: 'Create a bounded source-fix task in an isolated worktree when evidence points to a repo-harness defect.',
    class: 'source_defect_suspected',
    risk: 'high',
    confirmation: 'authorization',
    localOnly: true,
    boundedTo: ['repo_harness_source_repository'],
  },
  createPatchHandoff: {
    id: 'recovery.create_patch_handoff',
    title: 'Create patch handoff',
    description: 'Create a safe patch handoff artifact when client-side tool calls are blocked.',
    class: 'platform_blocked',
    risk: 'medium',
    confirmation: 'authorization',
    localOnly: true,
    boundedTo: ['repo_harness_artifact_storage'],
  },
} satisfies Record<string, RecoveryActionDescriptor>;

export function recoveryActionById(actionId: string): RecoveryActionDescriptor | undefined {
  return Object.values(RECOVERY_ACTIONS).find((action) => action.id === actionId);
}
